packages:
  - "."
  - "libro/core"
  - "libro/service"
  - "libro/chrome-extension"

allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@worldcoin/idkit-core@4.3.0'
  - '@worldcoin/idkit@4.3.0'
patchedDependencies:
  '@worldcoin/idkit-core@4.3.0': patches/@worldcoin__idkit-core@4.3.0.patch
