export const LIBRO_BROWSER_MCP_TOOLS = [
  'oauth_authorization_context',
  'oauth_authorize',
  "identity_context",
  "identity_verify",
  "identity_hint",
  "identity_handle",
  "browser_review",
  "user_operation_receipt",
  "sponsorship_context",
  "sponsorship_verify",
  "signing_context",
  "signing_prepare",
  "signing_relay",
  "signing_finalize",
  "signing_submission",
  "agent_signing_context",
  "agent_signing_prepare",
  "agent_signing_relay",
  "agent_signing_finalize",
  "handle_signing_context",
  "handle_signing_prepare",
  "handle_signing_relay",
  "handle_signing_finalize"
] as const
