CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE libro_identities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  world_id_session_id TEXT NOT NULL UNIQUE,
  session_commitment VARCHAR(66) NOT NULL UNIQUE,
  credential_identifier VARCHAR(255) NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_authors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_id UUID NOT NULL UNIQUE REFERENCES libro_identities(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  handle VARCHAR(32) NOT NULL UNIQUE,
  bio TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_oauth_clients (
  id TEXT PRIMARY KEY,
  client_type VARCHAR(16) NOT NULL CHECK (client_type IN ('public', 'confidential')),
  secret_hash CHAR(64),
  redirect_uris TEXT[] NOT NULL,
  resource TEXT NOT NULL,
  display_name VARCHAR(120),
  author_namespace TEXT,
  namespace_verified_at TIMESTAMPTZ,
  dynamically_registered BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ((client_type = 'confidential' AND secret_hash IS NOT NULL) OR client_type = 'public'),
  CHECK (author_namespace IS NULL OR namespace_verified_at IS NOT NULL)
);

CREATE TABLE libro_rp_contexts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nonce VARCHAR(66) NOT NULL UNIQUE,
  purpose VARCHAR(32) NOT NULL CHECK (purpose IN (
    'login', 'signup', 'publish', 'claim_handle', 'agent_registration', 'sponsorship'
  )),
  client_id TEXT REFERENCES libro_oauth_clients(id) ON DELETE SET NULL,
  identity_id UUID REFERENCES libro_identities(id) ON DELETE CASCADE,
  object_id TEXT,
  expected_signal_hash VARCHAR(78),
  expected_session_commitment VARCHAR(66),
  request_ip_hash CHAR(64),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX libro_rp_contexts_active ON libro_rp_contexts(expires_at) WHERE consumed_at IS NULL;
CREATE INDEX libro_rp_contexts_ip_created ON libro_rp_contexts(request_ip_hash, created_at)
  WHERE request_ip_hash IS NOT NULL;

CREATE TABLE libro_sponsorship_bindings (
  identity_id UUID PRIMARY KEY REFERENCES libro_identities(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  nullifier NUMERIC(78, 0) NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (action, nullifier)
);

CREATE TABLE libro_handle_claims (
  identity_id UUID PRIMARY KEY REFERENCES libro_identities(id) ON DELETE RESTRICT,
  handle VARCHAR(32) NOT NULL UNIQUE,
  handle_hash VARCHAR(66) NOT NULL UNIQUE,
  session_commitment VARCHAR(66) NOT NULL UNIQUE,
  transaction_hash VARCHAR(66) NOT NULL UNIQUE,
  finalized_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_handle_claim_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_id UUID NOT NULL REFERENCES libro_identities(id) ON DELETE RESTRICT,
  origin_client_id TEXT REFERENCES libro_oauth_clients(id) ON DELETE SET NULL,
  handle VARCHAR(32) NOT NULL,
  handle_hash VARCHAR(66) NOT NULL,
  signal_text TEXT NOT NULL,
  signal_hash VARCHAR(78) NOT NULL,
  signing_capability_hash CHAR(64) NOT NULL UNIQUE,
  proof JSONB,
  transaction JSONB,
  transaction_hash VARCHAR(66),
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_publish_challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_id UUID NOT NULL REFERENCES libro_identities(id) ON DELETE RESTRICT,
  author_id UUID NOT NULL REFERENCES libro_authors(id) ON DELETE RESTRICT,
  origin_client_id TEXT REFERENCES libro_oauth_clients(id) ON DELETE SET NULL,
  client_reference TEXT,
  nonce VARCHAR(66) NOT NULL UNIQUE,
  session_commitment VARCHAR(66) NOT NULL,
  signal_text TEXT NOT NULL,
  signal_hash VARCHAR(78) NOT NULL,
  publication JSONB NOT NULL,
  signing_capability_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX libro_publish_challenges_active ON libro_publish_challenges(expires_at) WHERE consumed_at IS NULL;

CREATE TABLE libro_publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id UUID NOT NULL,
  identity_id UUID NOT NULL,
  origin_client_id TEXT,
  client_reference TEXT,
  signal_hash VARCHAR(78) NOT NULL UNIQUE,
  authorship_class VARCHAR(16) NOT NULL CHECK (authorship_class IN ('human', 'agent')),
  signal JSONB NOT NULL,
  proof JSONB NOT NULL,
  version VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255),
  date TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX libro_publications_author_date ON libro_publications(author_id, date DESC);
CREATE INDEX libro_publications_origin_date ON libro_publications(origin_client_id, date DESC);
CREATE INDEX libro_publications_date ON libro_publications(date DESC);

CREATE TABLE libro_human_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  challenge_id UUID NOT NULL UNIQUE REFERENCES libro_publish_challenges(id) ON DELETE RESTRICT,
  signal_hash VARCHAR(78) NOT NULL,
  handle_hash VARCHAR(66) NOT NULL,
  session_commitment VARCHAR(66) NOT NULL,
  session_nullifier NUMERIC(78, 0) NOT NULL,
  chain_id INTEGER NOT NULL,
  registry_address VARCHAR(42) NOT NULL,
  proof JSONB NOT NULL,
  transaction JSONB NOT NULL,
  submission_method VARCHAR(24),
  user_op_hash VARCHAR(66),
  transaction_hash VARCHAR(66),
  publication_id BIGINT REFERENCES libro_publications(id) ON DELETE SET NULL,
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_agent_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_id UUID NOT NULL REFERENCES libro_identities(id) ON DELETE RESTRICT,
  author_id UUID NOT NULL REFERENCES libro_authors(id) ON DELETE RESTRICT,
  origin_client_id TEXT REFERENCES libro_oauth_clients(id) ON DELETE SET NULL,
  author_reference JSONB,
  registration_hash VARCHAR(66) NOT NULL UNIQUE,
  handle_hash VARCHAR(66) NOT NULL,
  session_commitment VARCHAR(66) NOT NULL,
  controller_address VARCHAR(42) NOT NULL,
  agent_address VARCHAR(42) NOT NULL,
  scope NUMERIC(78, 0) NOT NULL,
  valid_from TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  nonce VARCHAR(66) NOT NULL UNIQUE,
  signal TEXT NOT NULL,
  signal_hash VARCHAR(78) NOT NULL,
  payload JSONB NOT NULL,
  signing_capability_hash CHAR(64) NOT NULL UNIQUE,
  proof JSONB,
  chain_id INTEGER NOT NULL,
  registry_address VARCHAR(42) NOT NULL,
  transaction JSONB,
  user_op_hash VARCHAR(66),
  transaction_hash VARCHAR(66),
  finalized_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_agent_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_id UUID NOT NULL REFERENCES libro_agent_registrations(id) ON DELETE RESTRICT,
  publication_id BIGINT REFERENCES libro_publications(id) ON DELETE SET NULL,
  registration_hash VARCHAR(66) NOT NULL,
  handle_hash VARCHAR(66) NOT NULL,
  document_signal_hash VARCHAR(78) NOT NULL UNIQUE,
  document_signal_text TEXT NOT NULL,
  document_nonce VARCHAR(66) NOT NULL,
  signed_at TIMESTAMPTZ NOT NULL,
  agent_address VARCHAR(42) NOT NULL,
  agent_signature TEXT NOT NULL,
  publication JSONB NOT NULL,
  proof JSONB NOT NULL,
  chain_id INTEGER NOT NULL,
  registry_address VARCHAR(42) NOT NULL,
  transaction JSONB NOT NULL,
  user_op_hash VARCHAR(66),
  transaction_hash VARCHAR(66),
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_oauth_codes (
  code_hash CHAR(64) PRIMARY KEY,
  client_id TEXT NOT NULL REFERENCES libro_oauth_clients(id) ON DELETE CASCADE,
  identity_id UUID NOT NULL REFERENCES libro_identities(id) ON DELETE CASCADE,
  redirect_uri TEXT NOT NULL,
  resource TEXT NOT NULL,
  scope TEXT[] NOT NULL,
  code_challenge VARCHAR(128) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_oauth_grants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id TEXT NOT NULL REFERENCES libro_oauth_clients(id) ON DELETE CASCADE,
  identity_id UUID NOT NULL REFERENCES libro_identities(id) ON DELETE CASCADE,
  session_commitment VARCHAR(66) NOT NULL,
  handle VARCHAR(32) NOT NULL,
  resource TEXT NOT NULL,
  scope TEXT[] NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE libro_oauth_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grant_id UUID NOT NULL REFERENCES libro_oauth_grants(id) ON DELETE CASCADE,
  token_type VARCHAR(16) NOT NULL CHECK (token_type IN ('access', 'refresh')),
  token_hash CHAR(64) NOT NULL UNIQUE,
  resource TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX libro_oauth_tokens_active ON libro_oauth_tokens(expires_at, revoked_at);

CREATE TABLE libro_service_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type VARCHAR(64) NOT NULL,
  origin_client_id TEXT,
  aggregate_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at TIMESTAMPTZ
);

CREATE TABLE libro_event_deliveries (
  event_id UUID NOT NULL REFERENCES libro_service_events(id) ON DELETE CASCADE,
  destination TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at TIMESTAMPTZ,
  last_error TEXT,
  PRIMARY KEY (event_id, destination)
);
CREATE INDEX libro_event_deliveries_pending ON libro_event_deliveries(next_attempt_at) WHERE delivered_at IS NULL;

CREATE TABLE libro_copy_checkpoints (
  entity TEXT PRIMARY KEY,
  source_count BIGINT NOT NULL,
  last_source_modified_at TIMESTAMPTZ,
  copied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  report JSONB NOT NULL DEFAULT '{}'::jsonb
);
-- Historical authors have no invented World ID session and cannot authenticate.
ALTER TABLE libro_authors ALTER COLUMN identity_id DROP NOT NULL;
ALTER TABLE libro_publications ALTER COLUMN identity_id DROP NOT NULL;
ALTER TABLE libro_publications ADD COLUMN legacy_proof BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE libro_publications ADD CONSTRAINT libro_publications_identity_class_check
  CHECK (legacy_proof OR identity_id IS NOT NULL);
ALTER TABLE libro_publications ADD CONSTRAINT libro_publications_legacy_shape_check
  CHECK (NOT legacy_proof OR (
    authorship_class = 'human' AND NOT (signal ? 'publication_schema')
    AND proof->>'verification_level' = 'orb'
    AND proof ?& ARRAY['proof', 'merkle_root', 'nullifier_hash', 'verification_level']
  ));
